site_name: QM/MM - best practices
site_url: https://hpc2n.github.io/course-qmmm
site_description: Material for the course QM/MM - best practices
site_dir: site.build
theme:
  name: readthedocs
  locale: en
  logo: images/hpc2n-qmmm.png
    #  static_templates:
    #- sitemap.html
  include_sidebar: true
  font:
    code: Robot Mono
  features:
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  tabs: true
  language: en
extra_css:
  - css/extra.css
    #extra_javascript:
    #  - js/popper.min.js
    #  - js/tippy-bundle.umd.js
    #  - js/clipboard.js

nav:
  - Home: index.md
  - Introduction: intro.md
  - Classical MD simulations:
    - Basic concepts: classical.md
    - Running simulations: namd.md  
    - Analyzing simulations: vmd.md  
  - QM simulations: 
    - Basic concepts: quantum.md
  - QM/MM simulations: 
    - GAUSSIAN/ORCA: qmmm-gaussianorca.md
  - Summary: summary.md
plugins:
  - search
  - external-markdown
  - mkdocstrings
  - markdown-exec
  - open-in-new-tab
  - mermaid2

markdown_extensions:
  - toc:
      toc_depth: 1-2
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - smarty
  - tables
    #  - codehilite
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.blocks.caption
  #- pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
